services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network-account

  zookeeper:
    image: bitnami/zookeeper:3.8
    networks:
      - app-network-account
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka1:
    image: bitnami/kafka:3.6
    ports:
       - "9092:9092"
       - "29092:29092"
    volumes:
      - kafka_data1:/bitnami
    networks:
      - app-network-account
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9100:8080
    environment:
       KAFKA_CLUSTERS_0_NAME: local
       KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
       KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka1
    networks:
      - app-network-account

  account-service:
    build:
      context: ../accountservice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGODB_URL: mongodb://mongodb:27017/account-microservice
      KAFKA_CLIENT_ID: account-service
      KAFKA_BROKERS: kafka1:9092
      KAFKA_TOPIC: transaction-service-topic
      KAFKA_GROUP_ID: account-group
    depends_on:
      - mongodb
      - kafka1
    networks:
      - app-network-account

networks:
  app-network-account:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data1:
    driver: local
  mongodb_data:
